### ISSUE TITLE
As a user, I want to see the image of the musicians

### ISSUE THREAD

**Issue by RubySpeeders** [RubySpeeders/Drum-Roulette#4]
* for now, we can store the images of the US Navy Percussionists in files on the app. Eventually we will move to storing them either on S3 Buckets or on Lightsail. @charlottekies can tell us more about Lightsail and if that is the right move.
* for this ticket, the image should be a circle as in the figma file
* there are 9 musicians and we can get their images from the [website](https://www.navyband.navy.mil/ensembles/concert-band#roster)

**Comment by charlottekies** [comment]
I'm closing this issue because the navy images are all up now!
